import React, { useState } from 'react';
import { useSimulation } from '../context/SimulationContext';
import { AlertStatus } from '../types';
import { RiskBadge } from '../components/common/RiskBadge';
import {
  BellRing,
  CheckCircle2,
  Clock,
  ShieldCheck,
  Check,
  Radio,
  CloudRain,
  Mail,
  Send,
  ExternalLink
} from 'lucide-react';

export const AlertsPage: React.FC = () => {
  const {
    alerts,
    approveAlert,
    acknowledgeAlert,
    emails,
    openEmailModal,
    dispatchAlertEmail
  } = useSimulation();
  const [statusFilter, setStatusFilter] = useState<'ALL' | AlertStatus>('ALL');
  const [severityFilter, setSeverityFilter] = useState<'ALL' | 'SEVERE' | 'HIGH'>('ALL');
  const [sendingEmailForId, setSendingEmailForId] = useState<string | null>(null);

  const filteredAlerts = alerts.filter(a => {
    if (statusFilter !== 'ALL' && a.status !== statusFilter) return false;
    if (severityFilter !== 'ALL' && a.riskLevel !== severityFilter) return false;
    return true;
  });

  const pendingCount = alerts.filter(a => a.status === 'PENDING').length;
  const approvedCount = alerts.filter(a => a.status === 'APPROVED').length;
  const ackCount = alerts.filter(a => a.status === 'ACKNOWLEDGED').length;
  const hasSeverePending = alerts.some(a => a.status === 'PENDING' && a.riskLevel === 'SEVERE');

  return (
    <div className="space-y-4">
      {/* Console Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-command-800 pb-3">
        <div>
          <div className="flex items-center space-x-2">
            <BellRing className={`w-4 h-4 ${hasSeverePending ? 'text-rose-400 animate-pulse' : 'text-slate-400'}`} />
            <h2 className="text-base sm:text-lg font-bold font-display uppercase tracking-wider text-slate-100">
              Authority Alert Dispatch Console
            </h2>
          </div>
          <p className="text-xs text-slate-400 font-sans mt-0.5">
            Automated emergency broadcast proposals generated by the 50/25/15/10 deterministic risk engine requiring administrative authorization.
          </p>
        </div>

        {/* Telemetry Status Counters */}
        <div className="flex items-center space-x-1.5 font-mono text-xs">
          <div className={`px-2.5 py-1 rounded-xs border flex items-center space-x-1.5 ${
            pendingCount > 0 ? 'bg-rose-950/60 border-rose-500/50 text-rose-300' : 'bg-command-900 border-command-800 text-slate-400'
          }`}>
            <Clock className="w-3 h-3 text-rose-400" />
            <span>Pending: <strong className="tabular-nums">{pendingCount}</strong></span>
          </div>
          <div className="px-2.5 py-1 rounded-xs bg-command-900 border border-command-800 text-emerald-300 flex items-center space-x-1.5">
            <CheckCircle2 className="w-3 h-3 text-emerald-400" />
            <span>Authorized: <strong className="tabular-nums">{approvedCount}</strong></span>
          </div>
          <div className="px-2.5 py-1 rounded-xs bg-command-900 border border-command-800 text-slate-300 flex items-center space-x-1.5">
            <ShieldCheck className="w-3 h-3 text-sky-400" />
            <span>Archived: <strong className="tabular-nums">{ackCount}</strong></span>
          </div>
        </div>
      </div>

      {/* Executive Governance Banner */}
      <div className="bg-command-900 border border-command-750 p-3 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs font-mono">
        <div className="flex items-center space-x-2.5">
          <div className="w-7 h-7 rounded bg-command-950 border border-command-700 flex items-center justify-center text-sky-400 shrink-0">
            <Mail className="w-3.5 h-3.5" />
          </div>
          <div>
            <span className="font-bold text-slate-200">Two-Tier Executive Authorization Protocol:</span>
            <span className="text-slate-400 font-sans ml-1">
              Alerts can be dispatched to the State Emergency Operation Centre (SEOC) email inbox for executive sign-off, or overridden via direct command.
            </span>
          </div>
        </div>

        <button
          onClick={() => openEmailModal()}
          className="px-3 py-1.5 bg-sky-950/80 border border-sky-600/50 hover:bg-sky-900/80 text-sky-300 font-bold text-xs rounded-xs transition-colors shrink-0 flex items-center space-x-1.5 shadow-xs"
        >
          <Mail className="w-3.5 h-3.5" />
          <span>Open Authority Mailbox</span>
          {emails.filter(e => e.status === 'SENT').length > 0 && (
            <span className="px-1.5 py-0.2 rounded-full bg-rose-600 text-white text-[10px]">
              {emails.filter(e => e.status === 'SENT').length}
            </span>
          )}
        </button>
      </div>

      {/* Filter Tabs & Severity Dropdown */}
      <div className="flex flex-wrap items-center justify-between gap-2 bg-command-900 border border-command-800 p-1.5 text-xs font-mono">
        <div className="flex items-center space-x-1">
          <button
            onClick={() => setStatusFilter('ALL')}
            className={`px-2.5 py-1 rounded-xs transition-colors ${
              statusFilter === 'ALL' ? 'bg-command-800 text-slate-100 font-semibold' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            All Proposals ({alerts.length})
          </button>
          <button
            onClick={() => setStatusFilter('PENDING')}
            className={`px-2.5 py-1 rounded-xs transition-colors ${
              statusFilter === 'PENDING' ? 'bg-rose-950/80 border border-rose-600/60 text-rose-300 font-semibold' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Pending Review ({pendingCount})
          </button>
          <button
            onClick={() => setStatusFilter('APPROVED')}
            className={`px-2.5 py-1 rounded-xs transition-colors ${
              statusFilter === 'APPROVED' ? 'bg-emerald-950/80 border border-emerald-600/60 text-emerald-300 font-semibold' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Authorized ({approvedCount})
          </button>
          <button
            onClick={() => setStatusFilter('ACKNOWLEDGED')}
            className={`px-2.5 py-1 rounded-xs transition-colors ${
              statusFilter === 'ACKNOWLEDGED' ? 'bg-command-800 text-slate-200 font-semibold' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Archived ({ackCount})
          </button>
        </div>

        <div className="flex items-center space-x-1.5 pr-1">
          <span className="text-slate-500 uppercase text-[10px]">Filter Severity:</span>
          <select
            value={severityFilter}
            onChange={(e: any) => setSeverityFilter(e.target.value)}
            className="bg-command-950 border border-command-750 text-slate-200 rounded-xs px-2 py-0.5 text-xs font-mono focus:outline-none focus:border-sky-500"
          >
            <option value="ALL">All Severities</option>
            <option value="SEVERE">Severe Tier Only</option>
            <option value="HIGH">High Tier Only</option>
          </select>
        </div>
      </div>

      {/* Incident Cards List */}
      <div className="space-y-2.5">
        {filteredAlerts.length === 0 ? (
          <div className="bg-command-900 border border-command-800 p-12 text-center text-slate-400 font-mono">
            <ShieldCheck className="w-10 h-10 mx-auto text-emerald-400 mb-2 opacity-80" />
            <h4 className="text-sm font-bold text-slate-200 uppercase tracking-wider">
              Zero Incidents Requiring Authorization
            </h4>
            <p className="text-xs text-slate-500 mt-1 max-w-sm mx-auto font-sans">
              Switch simulation scenarios from the header or Demo Scenarios page to trigger dynamic flash flood warning generation.
            </p>
          </div>
        ) : (
          filteredAlerts.map(alert => {
            const isSevere = alert.riskLevel === 'SEVERE';
            const matchingEmail = emails.find(e => e.alertId === alert.id);

            return (
              <div
                key={alert.id}
                className={`bg-command-900 border border-command-800 border-l-4 ${
                  isSevere ? 'border-l-rose-500' : 'border-l-orange-500'
                } p-3.5 shadow-xl transition-colors hover:bg-command-850/60 font-mono`}
              >
                {/* Top Row: Village, Timing, Status */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-2 border-b border-command-800/80 pb-2.5">
                  <div className="flex items-center space-x-3">
                    <RiskBadge level={alert.riskLevel} size="md" score={alert.riskScore} />
                    <div>
                      <div className="flex items-center space-x-2">
                        <span className="font-bold text-sm text-slate-100">{alert.villageName}</span>
                        <span className="text-xs text-slate-400 font-normal">
                          ({alert.district} • Block: {alert.block})
                        </span>
                      </div>
                      <p className="text-[10px] text-slate-500 mt-0.5">
                        DISPATCH #{alert.id.slice(0, 8).toUpperCase()} • PROPOSED: {alert.createdAt} • POPULATION: {alert.population.toLocaleString()}
                      </p>
                    </div>
                  </div>

                  {/* Operational Status Tag */}
                  <div>
                    {alert.status === 'PENDING' && (
                      <span className="px-2 py-0.5 rounded-xs text-[10px] font-bold bg-amber-950/80 text-amber-300 border border-amber-500/40 inline-flex items-center space-x-1">
                        <Clock className="w-3 h-3" />
                        <span>ACTION REQUIRED: PENDING SIGN-OFF</span>
                      </span>
                    )}
                    {alert.status === 'APPROVED' && (
                      <span className="px-2 py-0.5 rounded-xs text-[10px] font-bold bg-emerald-950/80 text-emerald-300 border border-emerald-500/40 inline-flex items-center space-x-1">
                        <CheckCircle2 className="w-3 h-3" />
                        <span>AUTHORIZED BROADCAST</span>
                      </span>
                    )}
                    {alert.status === 'ACKNOWLEDGED' && (
                      <span className="px-2 py-0.5 rounded-xs text-[10px] font-bold bg-command-800 text-slate-300 border border-command-700 inline-flex items-center space-x-1">
                        <ShieldCheck className="w-3 h-3 text-sky-400" />
                        <span>LOGGED TO ARCHIVE</span>
                      </span>
                    )}
                  </div>
                </div>

                {/* Middle Row: Trigger Justification & Telemetry */}
                <div className="py-2.5 text-xs text-slate-300 flex flex-col md:flex-row justify-between gap-4">
                  <div className="space-y-1 flex-1">
                    <span className="text-[10px] uppercase tracking-wider text-slate-500 font-semibold block">
                      Deterministic Trigger Justification
                    </span>
                    <p className="text-xs text-slate-300 font-sans italic bg-command-950 p-2.5 border border-command-800/80 leading-relaxed">
                      "{alert.reason}"
                    </p>
                  </div>
                  <div className="text-[11px] text-slate-400 shrink-0 space-y-1 bg-command-950 p-2.5 border border-command-800/80">
                    <div className="flex justify-between space-x-4">
                      <span>Precipitation Rate:</span>
                      <strong className="text-sky-300 tabular-nums">{alert.rainfall.toFixed(1)} mm/hr</strong>
                    </div>
                    <div className="flex justify-between space-x-4">
                      <span>Warning Feed Status:</span>
                      <strong className="text-amber-400">{alert.warning}</strong>
                    </div>
                    {alert.approvedBy && (
                      <div className="flex justify-between space-x-4 pt-1 border-t border-command-800">
                        <span>Authorized By:</span>
                        <span className="text-emerald-300">{alert.approvedBy}</span>
                      </div>
                    )}
                  </div>
                </div>

                {/* Bottom Row: Actions */}
                <div className="pt-2 flex flex-wrap items-center justify-between gap-2 border-t border-command-800/60 text-xs">
                  <div className="text-[11px] text-slate-400">
                    {matchingEmail ? (
                      <span className="inline-flex items-center space-x-1 text-sky-300">
                        <Mail className="w-3 h-3" />
                        <span>Dispatched to {matchingEmail.recipient}</span>
                        {matchingEmail.status === 'APPROVED' && (
                          <span className="text-emerald-400 font-bold ml-1">• Signed Off via Email</span>
                        )}
                      </span>
                    ) : (
                      <span className="text-slate-500">Awaiting executive action</span>
                    )}
                  </div>

                  <div className="flex items-center space-x-2">
                    {alert.status === 'PENDING' && (
                      <>
                        {matchingEmail ? (
                          <button
                            onClick={() => openEmailModal(matchingEmail.id)}
                            className="px-3 py-1.5 bg-command-800 hover:bg-command-700 text-sky-300 font-medium transition-colors inline-flex items-center space-x-1.5 border border-command-700"
                          >
                            <Mail className="w-3.5 h-3.5 text-sky-400" />
                            <span>Review in Mailbox</span>
                          </button>
                        ) : (
                          <button
                            onClick={async () => {
                              setSendingEmailForId(alert.id);
                              try {
                                await dispatchAlertEmail(alert.id);
                                openEmailModal();
                              } finally {
                                setSendingEmailForId(null);
                              }
                            }}
                            disabled={sendingEmailForId === alert.id}
                            className="px-3 py-1.5 bg-command-800 hover:bg-command-700 text-slate-200 font-medium transition-colors inline-flex items-center space-x-1.5 border border-command-700"
                          >
                            <Send className="w-3.5 h-3.5 text-slate-400" />
                            <span>{sendingEmailForId === alert.id ? 'Dispatching...' : 'Dispatch to Email'}</span>
                          </button>
                        )}

                        <button
                          onClick={() => approveAlert(alert.id)}
                          className="px-3.5 py-1.5 bg-rose-700 hover:bg-rose-600 text-white font-bold transition-colors inline-flex items-center space-x-1.5 shadow-sm"
                        >
                          <Check className="w-3.5 h-3.5" />
                          <span>Authorize Direct</span>
                        </button>
                      </>
                    )}
                    {alert.status === 'APPROVED' && (
                      <button
                        onClick={() => acknowledgeAlert(alert.id)}
                        className="px-3.5 py-1.5 bg-sky-700 hover:bg-sky-600 text-white font-bold transition-colors inline-flex items-center space-x-1.5 shadow-sm"
                      >
                        <ShieldCheck className="w-3.5 h-3.5" />
                        <span>Acknowledge Protocol</span>
                      </button>
                    )}
                    {alert.status === 'ACKNOWLEDGED' && (
                      <span className="text-slate-500 text-[10px]">
                        ✓ Emergency broadcast execution confirmed and logged
                      </span>
                    )}
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
